let temp_pages_array = [
    {
        name: "none",
        cht: "請選擇頁面",
    },
    {
        name: "medicine_cart",
        cht: "住院藥車",
    }
];
let med_cart_return_data = [
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "6666666",
        cht: "大瓶藥例外",
        name: "big_bottle_exception",
        value_type: "checkbox",
        value: "True",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "44424242",
        cht: "顯示公藥",
        name: "display_public_medicine",
        value_type: "checkbox",
        value: "True",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "11111111",
        cht: "藥名(英)字體大小",
        name: "med_name_font_size",
        value_type: "radio",
        radio_option: ["16", "20", "24", "28", "36"],
        value: "20",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "14422222",
        cht: "藥名(中)字體大小",
        name: "med_cht_name_font_size",
        value_type: "text",
        value: "20",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "切帳時間",
        name: "cut_time",
        value_type: "time",
        value: "13:29",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "asdfasdf",
        cht: "交車時間",
        name: "delivery_time",
        value_type: "time",
        value: "15:32",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "顯示欄位(任選6個)",
        name: "display_block",
        limit: 6,
        value_type: "checkbox_group",
        value: [
            {
                name: "ordseq",
                cht: "序號",
                value: "True",
            },
            {
                name: "dosage",
                cht: "劑量",
                value: "True",
            },
            {
                name: "dunit",
                cht: "單位",
                value: "True",
            },
            {
                name: "freqn",
                cht: "頻次",
                value: "True",
            },
            {
                name: "route",
                cht: "途徑",
                value: "True",
            },
            {
                name: "code",
                cht: "藥碼",
                value: "True",
            },
            {
                name: "storage",
                cht: "儲位",
                value: "False",
            },
        ],
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "測試(任選3個)",
        name: "test_block",
        limit: 3,
        value_type: "checkbox_group",
        value: [
            {
                name: "ordseq",
                cht: "序號",
                value: "True",
            },
            {
                name: "dosage",
                cht: "劑量",
                value: "False",
            },
            {
                name: "dunit",
                cht: "單位",
                value: "True",
            },
            {
                name: "freqn",
                cht: "頻次",
                value: "True",
            },
            {
                name: "route",
                cht: "途徑",
                value: "False",
            },
            {
                name: "code",
                cht: "藥碼",
                value: "False",
            },
            {
                name: "storage",
                cht: "儲位",
                value: "False",
            },
        ],
    },
];
let temp_med_cart_return_data = [
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "6666666",
        cht: "大瓶藥例外",
        name: "big_bottle_exception",
        value_type: "checkbox",
        value: "True",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "44424242",
        cht: "顯示公藥",
        name: "display_public_medicine",
        value_type: "checkbox",
        value: "True",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "11111111",
        cht: "藥名(英)字體大小",
        name: "med_name_font_size",
        value_type: "radio",
        radio_option: ["16", "20", "24", "28", "36"],
        value: "20",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "14422222",
        cht: "藥名(中)字體大小",
        name: "med_cht_name_font_size",
        value_type: "text",
        value: "20",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "切帳時間",
        name: "cut_time",
        value_type: "time",
        value: "13:29",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "asdfasdf",
        cht: "交車時間",
        name: "delivery_time",
        value_type: "time",
        value: "15:32",
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "顯示欄位(任選6個)",
        name: "display_block",
        limit: 6,
        value_type: "checkbox_group",
        value: [
            {
                name: "ordseq",
                cht: "序號",
                value: "True",
            },
            {
                name: "dosage",
                cht: "劑量",
                value: "True",
            },
            {
                name: "dunit",
                cht: "單位",
                value: "True",
            },
            {
                name: "freqn",
                cht: "頻次",
                value: "True",
            },
            {
                name: "route",
                cht: "途徑",
                value: "True",
            },
            {
                name: "code",
                cht: "藥碼",
                value: "True",
            },
            {
                name: "storage",
                cht: "儲位",
                value: "False",
            },
        ],
    },
    {
        page_name: "medicine_cart",
        page_cht_name: "住院藥車",
        guid: "12345442",
        cht: "測試(任選3個)",
        name: "test_block",
        limit: 3,
        value_type: "checkbox_group",
        value: [
            {
                name: "ordseq",
                cht: "序號",
                value: "True",
            },
            {
                name: "dosage",
                cht: "劑量",
                value: "False",
            },
            {
                name: "dunit",
                cht: "單位",
                value: "True",
            },
            {
                name: "freqn",
                cht: "頻次",
                value: "True",
            },
            {
                name: "route",
                cht: "途徑",
                value: "False",
            },
            {
                name: "code",
                cht: "藥碼",
                value: "False",
            },
            {
                name: "storage",
                cht: "儲位",
                value: "False",
            },
        ],
    },
];
